# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('closed_at', models.CharField(blank=True, max_length=500)),
                ('created_at', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.CharField(blank=True, max_length=500)),
                ('number', models.IntegerField(blank=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('gateway', models.CharField(blank=True, max_length=250)),
                ('test', models.BooleanField(default=False)),
                ('total_price', models.CharField(blank=True, max_length=250)),
                ('subtotal_price', models.CharField(blank=True, max_length=250)),
                ('total_weight', models.IntegerField(blank=True)),
                ('total_tax', models.CharField(blank=True, max_length=250)),
                ('taxes_included', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('financial_status', models.CharField(blank=True, max_length=250)),
                ('confirmed', models.BooleanField(default=False)),
                ('total_discounts', models.CharField(blank=True, max_length=250)),
                ('total_line_items_price', models.CharField(blank=True, max_length=250)),
                ('cart_token', models.CharField(blank=True, max_length=250)),
                ('buyer_accepts_marketing', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('referring_site', models.CharField(blank=True, max_length=250)),
                ('landing_site', models.CharField(blank=True, max_length=250)),
                ('cancelled_at', models.CharField(blank=True, max_length=500)),
                ('cancel_reason', models.CharField(blank=True, max_length=250)),
                ('total_price_usd', models.CharField(blank=True, max_length=250)),
                ('checkout_token', models.CharField(blank=True, max_length=250)),
                ('reference', models.CharField(blank=True, max_length=250)),
                ('user_id', models.CharField(blank=True, max_length=250)),
                ('location_id', models.CharField(blank=True, max_length=250)),
                ('source_identifier', models.CharField(blank=True, max_length=250)),
                ('source_url', models.CharField(blank=True, max_length=250)),
                ('processed_at', models.CharField(blank=True, max_length=250)),
                ('device_id', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('customer_locale', models.CharField(blank=True, max_length=10)),
                ('app_id', models.CharField(blank=True, max_length=250)),
                ('browser_ip', models.CharField(blank=True, max_length=250)),
                ('landing_site_ref', models.CharField(blank=True, max_length=250)),
                ('order_number', models.IntegerField(blank=True)),
                ('discount_applications', models.CharField(blank=True, max_length=2500)),
                ('discount_codes', models.CharField(blank=True, max_length=1500)),
                ('note_attributes', models.CharField(blank=True, max_length=1500)),
                ('payment_gateway_names', models.CharField(blank=True, max_length=500)),
                ('processing_method', models.CharField(blank=True, max_length=250)),
                ('checkout_id', models.CharField(blank=True, max_length=250)),
                ('source_name', models.CharField(blank=True, max_length=250)),
                ('fulfillment_status', models.CharField(blank=True, max_length=250)),
                ('tax_lines', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('contact_email', models.CharField(blank=True, max_length=250)),
                ('order_status_url', models.CharField(blank=True, max_length=500)),
                ('presentment_currency', models.CharField(blank=True, max_length=250)),
                ('total_line_items_price_set', models.CharField(blank=True, max_length=1000)),
                ('total_discounts_set', models.CharField(blank=True, max_length=1000)),
                ('total_shipping_price_set', models.CharField(blank=True, max_length=1000)),
                ('subtotal_price_set', models.CharField(blank=True, max_length=1000)),
                ('total_price_set', models.CharField(blank=True, max_length=1000)),
                ('total_tax_set', models.CharField(blank=True, max_length=1000)),
                ('line_items', models.CharField(blank=True, max_length=5000)),
                ('shipping_lines', models.CharField(blank=True, max_length=1500)),
                ('billing_address', models.CharField(blank=True, max_length=1500)),
                ('shipping_address', models.CharField(blank=True, max_length=1500)),
                ('fulfillments', models.CharField(blank=True, max_length=1500)),
                ('refunds', models.CharField(blank=True, max_length=1500)),
                ('customer', models.CharField(blank=True, max_length=2500)),
            ],
        ),
    ]
