# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmedia', '0002_auto_20190809_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
