# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmedia', '0004_remove_shopifyorder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
